### ISSUE TITLE
ERROR!

### ISSUE THREAD

**Issue by NightFury10497** [anujshah1003/Transfer-Learning-in-keras---custom-data#9]
model = ResNet50(include_top=True, weights='imagenet')
Traceback (most recent call last):

  File "<ipython-input-51-ff2c5afdbcb2>", line 1, in <module>
    model = ResNet50(include_top=True, weights='imagenet')

  File "<ipython-input-43-c6bfde0b4ab6>", line 144, in ResNet50
    include_top=include_top)

TypeError: _obtain_input_shape() got an unexpected keyword argument 'include_top'

**Comment by braincs** [comment]
replace "include_top" as "require_flatten" in the resnet50. have a try

**Comment by AzwadAbid** [comment]
Keras 2.2 have some changes. Just do this and your program will work.

Change from:
from keras.applications.imagenet_utils import _obtain_input_shape

To:
from keras_applications.imagenet_utils import _obtain_input_shape

**Comment by AzwadAbid** [comment]
@NightFury10497
Keras 2.2 have some changes. Just do this and your program will work.

Change from:
from keras.applications.imagenet_utils import _obtain_input_shape

To:
from keras_applications.imagenet_utils import _obtain_input_shape
